export const testimonials = [
  { name: "Anonymous", date: "8th Mar, 2026", rating: 5, text: "First of all, Abhishek is a good listener. He responded to my questions in a non-judgemental manner and at the very same time he provided solutions to my problems. I recommend Abhishek to almost all Data and AI enthusiasts!!!", pinned: false, avatar: 1 },
  { name: "Madhu Moolchandani", date: "14th Feb, 2026", rating: 5, text: "", pinned: false, avatar: 2 },
  { name: "Ravindra Peddi", date: "4th Feb, 2026", rating: 5, text: "The resume make sense now and covers the requirement portion perfectly. thanks", pinned: false, avatar: 3 },
  { name: "Anonymous", date: "29th Jan, 2026", rating: 4, text: "Excellent knowledge of things customer looking forwards from you sir", pinned: false, avatar: 4 },
  { name: "Anonymous", date: "15th Jan, 2026", rating: 5, text: "Honest and helpful", pinned: false, avatar: 5 },
  { name: "Deepa Chandra", date: "10th Jan, 2026", rating: 5, text: "Thank you very much for taking out the time and discussing the future prospects with me. It was very helpful and now I’m looking forward to the sessions.", pinned: false, avatar: 6 },
  { name: "Soumya Suman", date: "27th Dec, 2025", rating: 5, text: "", pinned: false, avatar: 7 },
  { name: "Suchhanda Chakraborty", date: "17th Dec, 2025", rating: 5, text: "overall very good", pinned: false, avatar: 8 },
  { name: "Talat Firdous", date: "15th Dec, 2025", rating: 5, text: "I really need this and you give me.. Thank you", pinned: false, avatar: 9 },
  { name: "Anandini Srivastava", date: "9th Dec, 2025", rating: 5, text: "Very helpful, now let me try from my end then I come to know what I have missed. Because while doing stuff show the reallity.", pinned: false, avatar: 10 },
  { name: "Divyansh", date: "2nd Mar, 2026", rating: 5, text: "Very friendly mentor", pinned: false, avatar: 11 },
  { name: "Vinita V Mamarde", date: "8th Feb, 2026", rating: 5, text: "Thank you for the notes.", pinned: false, avatar: 12 },
  { name: "Kanchan Sharma", date: "2nd Feb, 2026", rating: 3, text: "", pinned: false, avatar: 13 },
  { name: "Nirali Devendra Vora", date: "21st Jan, 2026", rating: 5, text: "Abhishek was quite prompt and helpful.", pinned: false, avatar: 14 },
  { name: "Vikas Khairnar", date: "11th Jan, 2026", rating: 5, text: "Abhishek was very friendly and helpful while guiding. He helped me correctly to understand my roadmap and what is exactly expected from me.", pinned: false, avatar: 15 },
  { name: "SUMAN KUMAR THAKUR", date: "10th Jan, 2026", rating: 4, text: "Great support and clear answers. This will definetly help me in next upcoming session", pinned: false, avatar: 16 },
  { name: "M.Revathi", date: "26th Dec, 2025", rating: 5, text: "", pinned: false, avatar: 17 },
  { name: "Anonymous", date: "17th Dec, 2025", rating: 5, text: "The resume format was exactly the same as I was looking for. Absolutely loved it. Thank you Abhishek sir 🙏🏻❤️", pinned: true, avatar: 18 },
  { name: "Anonymous", date: "15th Dec, 2025", rating: 4, text: "Useful", pinned: false, avatar: 19 },
  { name: "Anonymous", date: "9th Dec, 2025", rating: 5, text: "Good to connect one on one", pinned: false, avatar: 20 },
  { name: "Smita Santosh Soni", date: "2nd Dec, 2025", rating: 5, text: "My queries were addressed with great insights! I got exactly what I wanted from the session and I recommend him 100%, to anyone looking for guidance in Data Science career space.", pinned: true, avatar: 21 },
  { name: "Gaurav Kamboj", date: "1st Dec, 2025", rating: 5, text: "It was a good session", pinned: false, avatar: 22 },
  { name: "Anandini Srivastava", date: "25th Nov, 2025", rating: 5, text: "Helpful", pinned: false, avatar: 23 },
  { name: "Dinesh Patne", date: "6th Aug, 2025", rating: 5, text: "Nice", pinned: false, avatar: 24 },
  { name: "Anonymous", date: "23rd Jun, 2025", rating: 5, text: "Insightful session with great tips!", pinned: false, avatar: 25 },
  { name: "Atharva Jagtap", date: "7th Jun, 2025", rating: 5, text: "", pinned: false, avatar: 26 },
  { name: "Arun", date: "3rd May, 2025", rating: 5, text: "", pinned: false, avatar: 27 },
  { name: "Dhanush chalicheemala", date: "24th Jan, 2025", rating: 5, text: "The session provided me with clear direction on how to align my skills with my career goals and actionable steps to achieve them. My mentor shared valuable industry insights and offered practical advice tailored to my aspirations.", pinned: true, avatar: 28 },
  { name: "Akshay Dambhare", date: "19th Dec, 2024", rating: 5, text: "Abhishek provided an incredibly insightful session, giving me a clear perspective on my career path. He shared a well-structured 3-step roadmap for transitioning careers, each step detailed and actionable. His guidance was practical and encouraging, and I’m grateful for his expertise. Thank you, Abhishek!", pinned: true, avatar: 29 },
  { name: "chinmaya nayak", date: "13th Nov, 2024", rating: 5, text: "", pinned: false, avatar: 30 },
  { name: "Bhanu Pratap Maharishi", date: "2nd Dec, 2025", rating: 5, text: "Will love to connect again", pinned: false, avatar: 31 },
  { name: "Sriram M", date: "29th Nov, 2025", rating: 5, text: "It was a great experience in discussing with Abhishek about the nuances in research", pinned: false, avatar: 32 },
  { name: "Avi Goyal", date: "19th Nov, 2025", rating: 5, text: "", pinned: false, avatar: 33 },
  { name: "Anonymous", date: "8th Jul, 2025", rating: 5, text: "Answered all questions in depth", pinned: false, avatar: 34 },
  { name: "Pavan Chauhan", date: "8th Jun, 2025", rating: 5, text: "Abhishek has good AI/ML knowledge", pinned: false, avatar: 35 },
  { name: "Abhishek Swami", date: "5th Jun, 2025", rating: 5, text: "", pinned: false, avatar: 36 },
  { name: "Kalpesh Prakash", date: "31st Jan, 2025", rating: 5, text: "Had a great conversation with Abhishek, who shared his insights on the role and helped me evaluate which offer to accept.", pinned: false, avatar: 37 },
  { name: "Sameer Sarkate", date: "6th Jan, 2025", rating: 5, text: "very informative and helpful session", pinned: false, avatar: 38 },
  { name: "Vishvambhar Kulkarni", date: "21st Nov, 2024", rating: 5, text: "It was a great conversation with Abhishek. He shared very important insights and explained key issues related to my queries.", pinned: true, avatar: 39 },
  { name: "Gaurav Dattu Mahajan", date: "7th Nov, 2024", rating: 5, text: "Had a conversation with Abhishek about the Business Analyst profile, and he provided a comprehensive roadmap tailored to my background. His guidance was incredibly helpful, and I believe this will greatly support my career journey. Thank you Abhishek.", pinned: true, avatar: 40 },
  { name: "Anonymous", date: "7th Nov, 2024", rating: 5, text: "Abhishek gave me good road map for my requirements want to connect with him for future development thank you Abhishek", pinned: false, avatar: 41 },
  { name: "Sandesh", date: "9th Jul, 2024", rating: 5, text: "", pinned: false, avatar: 42 },
  { name: "Arun Kumar", date: "2nd Jun, 2024", rating: 5, text: "Good Explanation", pinned: false, avatar: 43 },
  { name: "chinmaya nayak", date: "6th Oct, 2024", rating: 5, text: "", pinned: false, avatar: 44 },
  { name: "Sandesh", date: "22nd Jun, 2024", rating: 5, text: "The best", pinned: false, avatar: 45 },
  { name: "Vasanth", date: "6th Feb, 2024", rating: 5, text: "", pinned: false, avatar: 46 }
];
